FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    dash==2.17.1 \
    dash-bootstrap-components==1.6.0 \
    plotly==5.22.0 \
    pandas==2.2.2 \
    pyarrow==16.1.0 \
    deltalake==0.18.2 \
    statsmodels==0.14.2 \
    "kafka-python>=2.0.2"

COPY dashboard/ ./dashboard/

EXPOSE 8050

CMD ["python", "dashboard/app.py"]
